### ISSUE TITLE
Create a carousel

### ISSUE THREAD

**Issue by areebhammad** [areebhammad/HF2022#13]
- Create a carousel to the banner image
- You are allowed to replicate the same banner for slides 
- Adding new banners is optional

**Comment by Harsh-Singh-Rajput** [comment]
@areebhammad can we use CSS libraries for site like bootstrap for the creation of carousal

**Comment by areebhammad** [comment]
Yes, you can use bootstrap if you want to @Harsh-Singh-Rajput

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?

**Comment by Harsh-Singh-Rajput** [comment]
> Yes, you can use bootstrap if you want to @Harsh-Singh-Rajput

@areebhammad  Thanks then I will start working on it.
Assign this to me.

`UPDATE`
I have made a PR please look into it and review it
