### ISSUE TITLE
Create a footer

### ISSUE THREAD

**Issue by areebhammad** [areebhammad/HF2022#4]

**Comment by sarvesh2902** [comment]
Hi! I would like to work on this issue. Can you please assign it to me? @areebhammad

**Comment by Utkarsh404-crypto** [comment]
hey @areebhammad I would like to add the footer in the page. Can you assign me this task?

**Comment by octosapien** [comment]
I would love to work on this .
Could you assign me this issue ?

**Comment by salonisuman06** [comment]
Hi! I would like to work on this issue. Can you please assign it to me? @areebhammad
